name: "auto-merge"
on: [pull_request_target]

permissions:
  # Approve and comment pull request.
  pull-requests: write

jobs:
  auto-merge:
    uses: mdn/workflows/.github/workflows/auto-merge.yml@main
    with:
      target-repo: "mdn/workflows"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
