name: "auto-merge"
on: [pull_request_target]

jobs:
  auto-merge:
    uses: yusn/workflows/.github/workflows/auto-merge.yml@main
    with:
      target-repo: "yusn/workflows"
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
