name: json-lint

on:
  workflow_call:
    inputs:
      target-repo:
        description: The repo to run this action on. This is to prevent actions from running on forks unless intended.
        required: true
        type: string
      node-version:
        description: The node version to setup and use.
        default: 18
        required: false
        type: number
      cache:
        description: Which package manager cache to use
        default: "yarn"
        required: false
        type: string

jobs:
  json-lint:
    if: github.repository == ${{ inputs.target-repo }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache }}

      - name: Lint JSON files
        run: |
          npm install --no-save eslint eslint-plugin-json
          npx eslint . --ext .json
