name: welcome-bot

on:
  workflow_call:
    inputs:
      target-repo:
        description: The repo to run this action on. This is to prevent actions from running on forks unless intended.
        required: true
        type: string
      issue-welcome:
        description: Message to show to a contributor opening their first issue.
        required: false
        type: string
      pr-welcome:
        description: Message to show to a contributor opening their first pull request.
        required: false
        type: string

permissions:
  contents: none
  issues: write
  pull-requests: write

permissions:
  # Post comment in issue.
  issues: write
  # Post comment in pull request.
  pull-requests: write

jobs:
  welcome-bot:
    if: github.repository == inputs.target-repo
    name: The MDN Web Docs welcome bot
    runs-on: ubuntu-latest

    steps:
      - name: welcome-bot
        uses: actions/first-interaction@v1.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: ${{ inputs.issue-welcome }}
          pr-message: ${{ inputs.pr-welcome }}
